# Generated by Django 4.1.5 on 2023-01-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('business_name', models.CharField(blank=True, max_length=40)),
                ('email_address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('monthly_charge', models.FloatField()),
                ('contract_start_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('MONTH', 'Monthly'), ('ANNUAL', 'Annually'), ('QUARTERLY', '3mos'), ('SEMESTERLY', '6mos')], default='MONTH', max_length=40)),
                ('last_date_paid', models.DateField()),
                ('last_covered_date', models.DateField()),
                ('documents', models.URLField(blank=True)),
                ('is_reporting_as_business', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_width', models.FloatField()),
                ('dimension_length', models.FloatField()),
                ('dimension_height', models.FloatField(default=3)),
                ('unit_number', models.IntegerField(unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('payment_destination', models.CharField(choices=[('BBVA', 'BBVA'), ('Azteca - Ziomara', 'Azteca - Ziomara'), ('Costco Citibanamex - Layla', 'Costco Citibanamex - Layla'), ('Oro Citibanamex - Layla', 'Oro Citibanamex - Layla'), ('Costco Citibanamex - Raul', 'Costco Citibanamex - Raul'), ('Santander - Raul', 'Santander - Raul')], max_length=30)),
                ('client', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='self_storage_admin.client')),
                ('unit_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='self_storage_admin.unit')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='unit_access',
            field=models.ManyToManyField(default=None, related_name='units', to='self_storage_admin.unit'),
        ),
    ]
